export const REPOS = [
    {
        "id": 28457823,
        "node_id": "MDEwOlJlcG9zaXRvcnkyODQ1NzgyMw==",
        "name": "freeCodeCamp",
        "full_name": "freeCodeCamp/freeCodeCamp",
        "private": false,
        "owner": {
            "login": "freeCodeCamp",
            "id": 9892522,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjk4OTI1MjI=",
            "avatar_url": "https://avatars.githubusercontent.com/u/9892522?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/freeCodeCamp",
            "html_url": "https://github.com/freeCodeCamp",
            "followers_url": "https://api.github.com/users/freeCodeCamp/followers",
            "following_url": "https://api.github.com/users/freeCodeCamp/following{/other_user}",
            "gists_url": "https://api.github.com/users/freeCodeCamp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/freeCodeCamp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/freeCodeCamp/subscriptions",
            "organizations_url": "https://api.github.com/users/freeCodeCamp/orgs",
            "repos_url": "https://api.github.com/users/freeCodeCamp/repos",
            "events_url": "https://api.github.com/users/freeCodeCamp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/freeCodeCamp/received_events",
            "type": "Organization",
            "site_admin": false
        },
        "html_url": "https://github.com/freeCodeCamp/freeCodeCamp",
        "description": "freeCodeCamp.org's open-source codebase and curriculum. Learn to code for free.",
        "fork": false,
        "url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp",
        "forks_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/forks",
        "keys_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/teams",
        "hooks_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/hooks",
        "issue_events_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/issues/events{/number}",
        "events_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/events",
        "assignees_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/assignees{/user}",
        "branches_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/branches{/branch}",
        "tags_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/tags",
        "blobs_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/languages",
        "stargazers_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/stargazers",
        "contributors_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/contributors",
        "subscribers_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/subscribers",
        "subscription_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/subscription",
        "commits_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/contents/{+path}",
        "compare_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/merges",
        "archive_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/downloads",
        "issues_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/issues{/number}",
        "pulls_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/labels{/name}",
        "releases_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/releases{/id}",
        "deployments_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/deployments",
        "created_at": "2014-12-24T17:49:19Z",
        "updated_at": "2024-09-23T13:35:39Z",
        "pushed_at": "2024-09-23T13:05:18Z",
        "git_url": "git://github.com/freeCodeCamp/freeCodeCamp.git",
        "ssh_url": "git@github.com:freeCodeCamp/freeCodeCamp.git",
        "clone_url": "https://github.com/freeCodeCamp/freeCodeCamp.git",
        "svn_url": "https://github.com/freeCodeCamp/freeCodeCamp",
        "homepage": "http://contribute.freecodecamp.org/intro",
        "size": 455164,
        "stargazers_count": 402130,
        "watchers_count": 402130,
        "language": "TypeScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 37241,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 303,
        "license": {
            "key": "bsd-3-clause",
            "name": "BSD 3-Clause \"New\" or \"Revised\" License",
            "spdx_id": "BSD-3-Clause",
            "url": "https://api.github.com/licenses/bsd-3-clause",
            "node_id": "MDc6TGljZW5zZTU="
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "careers",
            "certification",
            "community",
            "curriculum",
            "d3",
            "education",
            "freecodecamp",
            "hacktoberfest",
            "javascript",
            "learn-to-code",
            "math",
            "nodejs",
            "nonprofits",
            "programming",
            "react",
            "teachers"
        ],
        "visibility": "public",
        "forks": 37241,
        "open_issues": 303,
        "watchers": 402130,
        "default_branch": "main",
        "score": 1.0
    },
    {
        "id": 85077558,
        "node_id": "MDEwOlJlcG9zaXRvcnk4NTA3NzU1OA==",
        "name": "developer-roadmap",
        "full_name": "kamranahmedse/developer-roadmap",
        "private": false,
        "owner": {
            "login": "kamranahmedse",
            "id": 4921183,
            "node_id": "MDQ6VXNlcjQ5MjExODM=",
            "avatar_url": "https://avatars.githubusercontent.com/u/4921183?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/kamranahmedse",
            "html_url": "https://github.com/kamranahmedse",
            "followers_url": "https://api.github.com/users/kamranahmedse/followers",
            "following_url": "https://api.github.com/users/kamranahmedse/following{/other_user}",
            "gists_url": "https://api.github.com/users/kamranahmedse/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/kamranahmedse/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/kamranahmedse/subscriptions",
            "organizations_url": "https://api.github.com/users/kamranahmedse/orgs",
            "repos_url": "https://api.github.com/users/kamranahmedse/repos",
            "events_url": "https://api.github.com/users/kamranahmedse/events{/privacy}",
            "received_events_url": "https://api.github.com/users/kamranahmedse/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/kamranahmedse/developer-roadmap",
        "description": "Interactive roadmaps, guides and other educational content to help developers grow in their careers.",
        "fork": false,
        "url": "https://api.github.com/repos/kamranahmedse/developer-roadmap",
        "forks_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/forks",
        "keys_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/teams",
        "hooks_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/hooks",
        "issue_events_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/issues/events{/number}",
        "events_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/events",
        "assignees_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/assignees{/user}",
        "branches_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/branches{/branch}",
        "tags_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/tags",
        "blobs_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/languages",
        "stargazers_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/stargazers",
        "contributors_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/contributors",
        "subscribers_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/subscribers",
        "subscription_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/subscription",
        "commits_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/contents/{+path}",
        "compare_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/merges",
        "archive_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/downloads",
        "issues_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/issues{/number}",
        "pulls_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/labels{/name}",
        "releases_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/releases{/id}",
        "deployments_url": "https://api.github.com/repos/kamranahmedse/developer-roadmap/deployments",
        "created_at": "2017-03-15T13:45:52Z",
        "updated_at": "2024-09-23T13:44:08Z",
        "pushed_at": "2024-09-23T12:54:52Z",
        "git_url": "git://github.com/kamranahmedse/developer-roadmap.git",
        "ssh_url": "git@github.com:kamranahmedse/developer-roadmap.git",
        "clone_url": "https://github.com/kamranahmedse/developer-roadmap.git",
        "svn_url": "https://github.com/kamranahmedse/developer-roadmap",
        "homepage": "https://roadmap.sh",
        "size": 238893,
        "stargazers_count": 292158,
        "watchers_count": 292158,
        "language": "TypeScript",
        "has_issues": true,
        "has_projects": false,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 38647,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 49,
        "license": {
            "key": "other",
            "name": "Other",
            "spdx_id": "NOASSERTION",
            "url": null,
            "node_id": "MDc6TGljZW5zZTA="
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "angular-roadmap",
            "backend-roadmap",
            "blockchain-roadmap",
            "computer-science",
            "dba-roadmap",
            "developer-roadmap",
            "devops-roadmap",
            "frontend-roadmap",
            "go-roadmap",
            "java-roadmap",
            "javascript-roadmap",
            "nodejs-roadmap",
            "python-roadmap",
            "qa-roadmap",
            "react-roadmap",
            "roadmap",
            "software-architect-roadmap",
            "vue-roadmap"
        ],
        "visibility": "public",
        "forks": 38647,
        "open_issues": 49,
        "watchers": 292158,
        "default_branch": "master",
        "score": 1.0
    },
    {
        "id": 11730342,
        "node_id": "MDEwOlJlcG9zaXRvcnkxMTczMDM0Mg==",
        "name": "vue",
        "full_name": "vuejs/vue",
        "private": false,
        "owner": {
            "login": "vuejs",
            "id": 6128107,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjYxMjgxMDc=",
            "avatar_url": "https://avatars.githubusercontent.com/u/6128107?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vuejs",
            "html_url": "https://github.com/vuejs",
            "followers_url": "https://api.github.com/users/vuejs/followers",
            "following_url": "https://api.github.com/users/vuejs/following{/other_user}",
            "gists_url": "https://api.github.com/users/vuejs/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/vuejs/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/vuejs/subscriptions",
            "organizations_url": "https://api.github.com/users/vuejs/orgs",
            "repos_url": "https://api.github.com/users/vuejs/repos",
            "events_url": "https://api.github.com/users/vuejs/events{/privacy}",
            "received_events_url": "https://api.github.com/users/vuejs/received_events",
            "type": "Organization",
            "site_admin": false
        },
        "html_url": "https://github.com/vuejs/vue",
        "description": "This is the repo for Vue 2. For Vue 3, go to https://github.com/vuejs/core",
        "fork": false,
        "url": "https://api.github.com/repos/vuejs/vue",
        "forks_url": "https://api.github.com/repos/vuejs/vue/forks",
        "keys_url": "https://api.github.com/repos/vuejs/vue/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/vuejs/vue/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/vuejs/vue/teams",
        "hooks_url": "https://api.github.com/repos/vuejs/vue/hooks",
        "issue_events_url": "https://api.github.com/repos/vuejs/vue/issues/events{/number}",
        "events_url": "https://api.github.com/repos/vuejs/vue/events",
        "assignees_url": "https://api.github.com/repos/vuejs/vue/assignees{/user}",
        "branches_url": "https://api.github.com/repos/vuejs/vue/branches{/branch}",
        "tags_url": "https://api.github.com/repos/vuejs/vue/tags",
        "blobs_url": "https://api.github.com/repos/vuejs/vue/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/vuejs/vue/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/vuejs/vue/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/vuejs/vue/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/vuejs/vue/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/vuejs/vue/languages",
        "stargazers_url": "https://api.github.com/repos/vuejs/vue/stargazers",
        "contributors_url": "https://api.github.com/repos/vuejs/vue/contributors",
        "subscribers_url": "https://api.github.com/repos/vuejs/vue/subscribers",
        "subscription_url": "https://api.github.com/repos/vuejs/vue/subscription",
        "commits_url": "https://api.github.com/repos/vuejs/vue/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/vuejs/vue/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/vuejs/vue/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/vuejs/vue/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/vuejs/vue/contents/{+path}",
        "compare_url": "https://api.github.com/repos/vuejs/vue/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/vuejs/vue/merges",
        "archive_url": "https://api.github.com/repos/vuejs/vue/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/vuejs/vue/downloads",
        "issues_url": "https://api.github.com/repos/vuejs/vue/issues{/number}",
        "pulls_url": "https://api.github.com/repos/vuejs/vue/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/vuejs/vue/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/vuejs/vue/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/vuejs/vue/labels{/name}",
        "releases_url": "https://api.github.com/repos/vuejs/vue/releases{/id}",
        "deployments_url": "https://api.github.com/repos/vuejs/vue/deployments",
        "created_at": "2013-07-29T03:24:51Z",
        "updated_at": "2024-09-23T13:34:10Z",
        "pushed_at": "2024-08-21T13:01:25Z",
        "git_url": "git://github.com/vuejs/vue.git",
        "ssh_url": "git@github.com:vuejs/vue.git",
        "clone_url": "https://github.com/vuejs/vue.git",
        "svn_url": "https://github.com/vuejs/vue",
        "homepage": "http://v2.vuejs.org",
        "size": 32231,
        "stargazers_count": 207723,
        "watchers_count": 207723,
        "language": "TypeScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 33675,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 603,
        "license": {
            "key": "mit",
            "name": "MIT License",
            "spdx_id": "MIT",
            "url": "https://api.github.com/licenses/mit",
            "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "framework",
            "frontend",
            "javascript",
            "vue"
        ],
        "visibility": "public",
        "forks": 33675,
        "open_issues": 603,
        "watchers": 207723,
        "default_branch": "main",
        "score": 1.0
    },
    {
        "id": 41881900,
        "node_id": "MDEwOlJlcG9zaXRvcnk0MTg4MTkwMA==",
        "name": "vscode",
        "full_name": "microsoft/vscode",
        "private": false,
        "owner": {
            "login": "microsoft",
            "id": 6154722,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjYxNTQ3MjI=",
            "avatar_url": "https://avatars.githubusercontent.com/u/6154722?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/microsoft",
            "html_url": "https://github.com/microsoft",
            "followers_url": "https://api.github.com/users/microsoft/followers",
            "following_url": "https://api.github.com/users/microsoft/following{/other_user}",
            "gists_url": "https://api.github.com/users/microsoft/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/microsoft/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/microsoft/subscriptions",
            "organizations_url": "https://api.github.com/users/microsoft/orgs",
            "repos_url": "https://api.github.com/users/microsoft/repos",
            "events_url": "https://api.github.com/users/microsoft/events{/privacy}",
            "received_events_url": "https://api.github.com/users/microsoft/received_events",
            "type": "Organization",
            "site_admin": false
        },
        "html_url": "https://github.com/microsoft/vscode",
        "description": "Visual Studio Code",
        "fork": false,
        "url": "https://api.github.com/repos/microsoft/vscode",
        "forks_url": "https://api.github.com/repos/microsoft/vscode/forks",
        "keys_url": "https://api.github.com/repos/microsoft/vscode/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/microsoft/vscode/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/microsoft/vscode/teams",
        "hooks_url": "https://api.github.com/repos/microsoft/vscode/hooks",
        "issue_events_url": "https://api.github.com/repos/microsoft/vscode/issues/events{/number}",
        "events_url": "https://api.github.com/repos/microsoft/vscode/events",
        "assignees_url": "https://api.github.com/repos/microsoft/vscode/assignees{/user}",
        "branches_url": "https://api.github.com/repos/microsoft/vscode/branches{/branch}",
        "tags_url": "https://api.github.com/repos/microsoft/vscode/tags",
        "blobs_url": "https://api.github.com/repos/microsoft/vscode/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/microsoft/vscode/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/microsoft/vscode/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/microsoft/vscode/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/microsoft/vscode/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/microsoft/vscode/languages",
        "stargazers_url": "https://api.github.com/repos/microsoft/vscode/stargazers",
        "contributors_url": "https://api.github.com/repos/microsoft/vscode/contributors",
        "subscribers_url": "https://api.github.com/repos/microsoft/vscode/subscribers",
        "subscription_url": "https://api.github.com/repos/microsoft/vscode/subscription",
        "commits_url": "https://api.github.com/repos/microsoft/vscode/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/microsoft/vscode/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/microsoft/vscode/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/microsoft/vscode/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/microsoft/vscode/contents/{+path}",
        "compare_url": "https://api.github.com/repos/microsoft/vscode/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/microsoft/vscode/merges",
        "archive_url": "https://api.github.com/repos/microsoft/vscode/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/microsoft/vscode/downloads",
        "issues_url": "https://api.github.com/repos/microsoft/vscode/issues{/number}",
        "pulls_url": "https://api.github.com/repos/microsoft/vscode/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/microsoft/vscode/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/microsoft/vscode/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/microsoft/vscode/labels{/name}",
        "releases_url": "https://api.github.com/repos/microsoft/vscode/releases{/id}",
        "deployments_url": "https://api.github.com/repos/microsoft/vscode/deployments",
        "created_at": "2015-09-03T20:23:38Z",
        "updated_at": "2024-09-23T13:48:06Z",
        "pushed_at": "2024-09-23T13:47:58Z",
        "git_url": "git://github.com/microsoft/vscode.git",
        "ssh_url": "git@github.com:microsoft/vscode.git",
        "clone_url": "https://github.com/microsoft/vscode.git",
        "svn_url": "https://github.com/microsoft/vscode",
        "homepage": "https://code.visualstudio.com",
        "size": 948330,
        "stargazers_count": 162713,
        "watchers_count": 162713,
        "language": "TypeScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 28704,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 9969,
        "license": {
            "key": "mit",
            "name": "MIT License",
            "spdx_id": "MIT",
            "url": "https://api.github.com/licenses/mit",
            "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "editor",
            "electron",
            "microsoft",
            "typescript",
            "visual-studio-code"
        ],
        "visibility": "public",
        "forks": 28704,
        "open_issues": 9969,
        "watchers": 162713,
        "default_branch": "main",
        "score": 1.0
    },
    {
        "id": 62607227,
        "node_id": "MDEwOlJlcG9zaXRvcnk2MjYwNzIyNw==",
        "name": "tech-interview-handbook",
        "full_name": "yangshun/tech-interview-handbook",
        "private": false,
        "owner": {
            "login": "yangshun",
            "id": 1315101,
            "node_id": "MDQ6VXNlcjEzMTUxMDE=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1315101?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/yangshun",
            "html_url": "https://github.com/yangshun",
            "followers_url": "https://api.github.com/users/yangshun/followers",
            "following_url": "https://api.github.com/users/yangshun/following{/other_user}",
            "gists_url": "https://api.github.com/users/yangshun/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/yangshun/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/yangshun/subscriptions",
            "organizations_url": "https://api.github.com/users/yangshun/orgs",
            "repos_url": "https://api.github.com/users/yangshun/repos",
            "events_url": "https://api.github.com/users/yangshun/events{/privacy}",
            "received_events_url": "https://api.github.com/users/yangshun/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/yangshun/tech-interview-handbook",
        "description": "💯 Curated coding interview preparation materials for busy software engineers",
        "fork": false,
        "url": "https://api.github.com/repos/yangshun/tech-interview-handbook",
        "forks_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/forks",
        "keys_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/teams",
        "hooks_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/hooks",
        "issue_events_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/issues/events{/number}",
        "events_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/events",
        "assignees_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/assignees{/user}",
        "branches_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/branches{/branch}",
        "tags_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/tags",
        "blobs_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/languages",
        "stargazers_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/stargazers",
        "contributors_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/contributors",
        "subscribers_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/subscribers",
        "subscription_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/subscription",
        "commits_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/contents/{+path}",
        "compare_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/merges",
        "archive_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/downloads",
        "issues_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/issues{/number}",
        "pulls_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/labels{/name}",
        "releases_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/releases{/id}",
        "deployments_url": "https://api.github.com/repos/yangshun/tech-interview-handbook/deployments",
        "created_at": "2016-07-05T05:00:48Z",
        "updated_at": "2024-09-23T13:33:18Z",
        "pushed_at": "2024-09-22T03:16:01Z",
        "git_url": "git://github.com/yangshun/tech-interview-handbook.git",
        "ssh_url": "git@github.com:yangshun/tech-interview-handbook.git",
        "clone_url": "https://github.com/yangshun/tech-interview-handbook.git",
        "svn_url": "https://github.com/yangshun/tech-interview-handbook",
        "homepage": "https://www.techinterviewhandbook.org",
        "size": 32291,
        "stargazers_count": 117168,
        "watchers_count": 117168,
        "language": "TypeScript",
        "has_issues": true,
        "has_projects": false,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": true,
        "forks_count": 14577,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 42,
        "license": {
            "key": "mit",
            "name": "MIT License",
            "spdx_id": "MIT",
            "url": "https://api.github.com/licenses/mit",
            "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "algorithm",
            "algorithm-interview",
            "algorithm-interview-questions",
            "algorithms",
            "behavioral-interviews",
            "coding-interviews",
            "interview-practice",
            "interview-preparation",
            "interview-questions",
            "system-design"
        ],
        "visibility": "public",
        "forks": 14577,
        "open_issues": 42,
        "watchers": 117168,
        "default_branch": "main",
        "score": 1.0
    }
]